export const Scenary = [{"email":"kcunnah0@shutterfly.com","password":"J1kvFAOrE"},
{"email":"sphidgin1@yale.edu","password":"Qy6mfSNNf46L"},
{"email":"ddoherty2@godaddy.com","password":"JYk8jc5VA37g"},
{"email":"nstanborough3@cnn.com","password":"3HY2q2gaPl"},
{"email":"bphillcock4@bloglines.com","password":"q5r3t4x6"},
{"email":"gaizikovitz5@aol.com","password":"FQ9sAnC0"},
{"email":"yrugg6@biglobe.ne.jp","password":"vouGr0INm"},
{"email":"lbutterick7@engadget.com","password":"5CJe0y8bF"},
{"email":"rcasely8@xrea.com","password":"cMEHxCOpj6u"},
{"email":"dottery9@edublogs.org","password":"QmgUiH"}]